// 我的accessToken
export const accessToken = '85f65af3-8985-482a-8181-49c7d14e1bec'

// 主页数据
export const REQUEST_HOMEPAGE_DATA = 'REQUEST_HOMEPAGE_DATA'
export const REQUEST_SAGA_HOMEPAGE_DATA = 'REQUEST_SAGA_HOMEPAGE_DATA'

// 主题详情数据
export const REQUEST_DETAIL_DATA='REQUEST_DETAIL_DATA'
export const REQUEST_SAGE_DETAIL_DATA='REQUEST_SAGE_DETAIL_DATA'

// 登录
export const LOGIN ='LOGIN'

// 退出
export const LOGOUT = 'LOGOUT'

// 请求用户数据
export const REQUEST_USER_INFO ='REQUEST_USER_INFO'
export const REQUEST_SAGA_USER_INFO ='REQUEST_SAGA_USER_INFO'

// 获取用户收藏的主题
export const REQUEST_COLLECT_THEME ='REQUEST_COLLECT_THEME'
export const REQUEST_SAGA_COLLECT_THEME ='REQUEST_SAGA_COLLECT_THEME'
